---
- name: iptables | install packages
  yum:
    name:
    - iptables
    - iptables-services

- name: iptables | template out iptables config
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0644
  notify: restart iptables

- name: iptables | load br_netfilter on boot
  template:
    src: k8s.conf.j2
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: iptables | load br_netfilter now
  command:
    /sbin/modprobe br_netfilter

- name: iptables | let iptables see bridged traffic (k8s)
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  with_items:
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  when: '"k8s_cluster" in group_names'

- name: iptables | systemd
  systemd:
    name: iptables
    state: started
    enabled: yes

- name: iptables | flush handlers
  meta: flush_handlers
