---
- name: pihole | ensure stateful dirs exist
  file:
    name: /etc/pihole
    state: directory
    owner: root
    group: root
    mode: 0755

- name: pihole | podman based installation
  include: podman.yaml
  when:
  - ansible_distribution == 'Fedora'

- name: pihole | docker based installation
  include: docker.yaml
  when:
  - ansible_distribution == 'Debian'
