---
- block:
  - name: k8s/calico | tempfile
    tempfile:
      state: directory
    register: _k8s_calico_tempfile

  - name: k8s/calico | template yaml
    template:
      src: '{{ item }}.j2'
      dest: '{{ _k8s_calico_tempfile.path }}/{{ item }}'
      owner: root
      group: root
      mode: 0644
    loop:
    - tigera-operator.yaml
    - custom-resources.yaml

  - name: k8s/calico | apply
    command: >
      kubectl apply -f {{ _k8s_calico_tempfile.path }}/{{ item }}
    loop:
    - tigera-operator.yaml
    - custom-resources.yaml
    changed_when: yes

  - name: k8s/calico | check the operator is up and running
    include_role:
      name: k8s/checks/deployment
    vars:
      check_label: k8s-app=tigera-operator
      check_namespace: tigera-operator

  - name: k8s/calico | check tigerastatus calico
    command: >
      kubectl get tigerastatus calico \
      -o 'template={% raw %}{{ range .status.conditions }}
      {{ if eq .type "Available" }}
      {{ if eq .status "True" }}true{{ end }}
      {{ end }}
      {{ end }}'
      {% endraw %}
    register: _calico_tigerastatus_calico
    until: _calico_tigerastatus_calico.stdout | regex_replace(' ', '') == 'true'
    retries: 60
    delay: 2
    changed_when: no

  always:
  - name: k8s/calico | cleanup
    file:
      path: '{{ _k8s_calico_tempfile.path }}'
      state: absent
