---
- hosts: fkmvm_hypervisor
  gather_facts: yes
  become: yes
  roles:
  - role: firecracker_microvm/install
    tags:
    - fkmvm_install
  - role: firecracker_microvm//network_core_bridge
    tags:
    - fkmvm_network
