---
- include: centos8.yaml
  when:
  - ansible_distribution == 'CentOS'
  - ansible_distribution_major_version == '8'

- include: debian10.yaml
  when:
  - ansible_distribution == 'Debian'
  - ansible_distribution_major_version == '10'

- name: docker | flush handlers
  meta: flush_handlers
