---
- name: get real path to firecracker bin
  ansible.builtin.stat:
    path: '{{ fkmvm_firecracker_bin }}'
  register: _firecracker_bin_stat

- name: template systemd unit file
  ansible.builtin.template:
    src: firecracker@.service.j2
    dest: /etc/systemd/system/firecracker@.service
    owner: root
    group: root
    mode: 0644
  notify: systemd reload
